import type { Note } from '@/lib/supabase/types'

export interface ExportOptions {
  includeMetadata?: boolean
  includeTimestamps?: boolean
  includeSpeakers?: boolean
  includeActionItems?: boolean
}

export function exportToMarkdown(
  note: Note,
  options: ExportOptions = {}
): string {
  const {
    includeMetadata = true,
    includeActionItems = true,
  } = options

  let markdown = ''

  // Title
  markdown += `# ${note.title}\n\n`

  // Metadata (YAML frontmatter)
  if (includeMetadata) {
    markdown += '---\n'
    markdown += `date: ${new Date(note.created_at).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric'
    })}\n`
    markdown += `mode: ${note.mode}\n`
    if (note.tags && note.tags.length > 0) {
      markdown += `tags: [${note.tags.join(', ')}]\n`
    }
    markdown += '---\n\n'
  }

  // Summary
  if (note.summary) {
    markdown += '## Summary\n\n'
    markdown += `${note.summary}\n\n`
  }

  // Key Points
  const structure = note.structure as any
  if (structure?.keyPoints && Array.isArray(structure.keyPoints) && structure.keyPoints.length > 0) {
    markdown += '## Key Points\n\n'
    structure.keyPoints.forEach((point: string) => {
      markdown += `- ${point}\n`
    })
    markdown += '\n'
  }

  // Decisions (for brainstorming/meeting mode)
  if (structure?.decisions && structure.decisions.length > 0) {
    markdown += '## Decisions\n\n'
    structure.decisions.forEach((decision: string) => {
      markdown += `- ${decision}\n`
    })
    markdown += '\n'
  }

  // Questions (for brainstorming mode)
  if (structure?.questions && structure.questions.length > 0) {
    markdown += '## Questions & Follow-ups\n\n'
    structure.questions.forEach((question: string) => {
      markdown += `- ${question}\n`
    })
    markdown += '\n'
  }

  // Action Items
  if (includeActionItems && structure?.actionItems && structure.actionItems.length > 0) {
    markdown += '## Action Items\n\n'
    structure.actionItems.forEach((item: any) => {
      const assignee = item.assignee || item.assignee_name || 'Unassigned'
      const dueDate = item.dueDate || item.due_date
      const priority = item.priority ? ` [${item.priority.toUpperCase()}]` : ''

      markdown += `- [ ] **${item.title}**${priority}\n`
      if (item.description) {
        markdown += `  - ${item.description}\n`
      }
      markdown += `  - Assignee: ${assignee}\n`
      if (dueDate) {
        markdown += `  - Due: ${new Date(dueDate).toLocaleDateString()}\n`
      }
      markdown += '\n'
    })
  }

  // Full Transcript
  if (note.content) {
    markdown += '## Full Transcript\n\n'
    markdown += `${note.content}\n\n`
  }

  // Footer
  markdown += '---\n\n'
  markdown += `*Generated by FifthDraft on ${new Date().toLocaleDateString()}*\n`

  return markdown
}

export function downloadMarkdown(note: Note, options?: ExportOptions): void {
  const markdown = exportToMarkdown(note, options)
  const blob = new Blob([markdown], { type: 'text/markdown;charset=utf-8' })
  const url = URL.createObjectURL(blob)

  const link = document.createElement('a')
  link.href = url
  link.download = `${sanitizeFilename(note.title)}.md`
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)

  URL.revokeObjectURL(url)
}

function sanitizeFilename(filename: string): string {
  return filename
    .replace(/[^a-z0-9]/gi, '_')
    .replace(/_+/g, '_')
    .toLowerCase()
}
