'use client'

import { FileText, Target, Calendar, Users, DollarSign, TrendingUp, AlertTriangle, Download } from 'lucide-react'
import { ProjectBrief } from '@/lib/services/project-brief-generator'

interface ProjectBriefDisplayProps {
  brief: ProjectBrief
  noteTitle: string
}

export default function ProjectBriefDisplay({ brief, noteTitle }: ProjectBriefDisplayProps) {
  const handleDownload = async () => {
    try {
      // Create markdown content
      const markdown = `# ${brief.title}

## Executive Overview
${brief.overview}

## Goals & Objectives
${brief.goals.map((g, i) => `${i + 1}. ${g}`).join('\n')}

## Key Requirements
${brief.requirements.map(r => `- ${r}`).join('\n')}

## Timeline
${brief.timeline.map(phase => `
### ${phase.phase}
**Duration:** ${phase.duration}

**Deliverables:**
${phase.deliverables.map(d => `- ${d}`).join('\n')}
`).join('\n')}

## Resources Needed

### People & Skills
${brief.resources.people.map(p => `- ${p}`).join('\n')}

### Tools & Platforms
${brief.resources.tools.map(t => `- ${t}`).join('\n')}

### Budget
${brief.resources.budget}

## Success Metrics
${brief.successMetrics.map((m, i) => `${i + 1}. ${m}`).join('\n')}

## Risks & Mitigation

${brief.risks.map(r => `**Risk:** ${r.risk}
**Mitigation:** ${r.mitigation}`).join('\n\n')}

## Immediate Next Steps

${brief.nextSteps.map((s, i) => {
  const priorityEmoji = s.priority === 'high' ? '🔴' : s.priority === 'medium' ? '🟡' : '🟢'
  const owner = s.owner ? ` (Owner: ${s.owner})` : ''
  return `${i + 1}. ${priorityEmoji} ${s.step}${owner}`
}).join('\n')}

---
*Generated by FifthDraft Idea Studio*
`

      // Create blob and download
      const blob = new Blob([markdown], { type: 'text/markdown' })
      const url = window.URL.createObjectURL(blob)
      const link = document.createElement('a')
      link.href = url
      const safeFilename = noteTitle.replace(/[^a-z0-9\s]/gi, '').replace(/\s+/g, '-').toLowerCase()
      link.download = `${safeFilename}-project-brief.md`
      document.body.appendChild(link)
      link.click()
      document.body.removeChild(link)
      window.URL.revokeObjectURL(url)
    } catch (error) {
      console.error('Download failed:', error)
    }
  }

  return (
    <div className="bg-white/80 backdrop-blur-sm rounded-lg shadow-sm border-2 border-indigo-200 mb-6">
      {/* Header */}
      <div className="p-6 border-b border-indigo-100 bg-gradient-to-r from-indigo-50 to-blue-50">
        <div className="flex items-start justify-between">
          <div className="flex-1">
            <div className="flex items-center space-x-2 mb-2">
              <FileText className="w-6 h-6 text-indigo-600" />
              <h2 className="text-2xl font-bold text-indigo-900">Project Brief</h2>
            </div>
            <h3 className="text-xl font-semibold text-gray-800">{brief.title}</h3>
          </div>
          <button
            onClick={handleDownload}
            className="flex items-center space-x-2 px-4 py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 transition-colors shadow-sm"
          >
            <Download className="w-4 h-4" />
            <span>Download</span>
          </button>
        </div>
      </div>

      {/* Executive Overview */}
      <div className="p-6 border-b border-gray-100">
        <h3 className="text-lg font-semibold text-gray-900 mb-3 flex items-center">
          <div className="w-8 h-8 rounded-full bg-indigo-100 flex items-center justify-center mr-2">
            <FileText className="w-4 h-4 text-indigo-600" />
          </div>
          Executive Overview
        </h3>
        <p className="text-gray-700 leading-relaxed whitespace-pre-wrap">{brief.overview}</p>
      </div>

      {/* Goals & Objectives */}
      <div className="p-6 border-b border-gray-100 bg-gradient-to-r from-purple-50/30 to-indigo-50/30">
        <h3 className="text-lg font-semibold text-gray-900 mb-4 flex items-center">
          <div className="w-8 h-8 rounded-full bg-purple-100 flex items-center justify-center mr-2">
            <Target className="w-4 h-4 text-purple-600" />
          </div>
          Goals & Objectives
        </h3>
        <div className="space-y-3">
          {brief.goals.map((goal, idx) => (
            <div key={idx} className="flex items-start space-x-3 p-3 bg-white rounded-lg border border-purple-200">
              <span className="flex-shrink-0 w-6 h-6 rounded-full bg-purple-600 text-white text-sm font-bold flex items-center justify-center">
                {idx + 1}
              </span>
              <span className="text-gray-700 flex-1">{goal}</span>
            </div>
          ))}
        </div>
      </div>

      {/* Key Requirements */}
      <div className="p-6 border-b border-gray-100">
        <h3 className="text-lg font-semibold text-gray-900 mb-4">Key Requirements</h3>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
          {brief.requirements.map((req, idx) => (
            <div key={idx} className="flex items-start space-x-2 p-3 bg-gray-50 rounded-lg border border-gray-200">
              <span className="text-indigo-600 font-bold flex-shrink-0">✓</span>
              <span className="text-gray-700 text-sm">{req}</span>
            </div>
          ))}
        </div>
      </div>

      {/* Timeline */}
      <div className="p-6 border-b border-gray-100 bg-gradient-to-r from-blue-50/30 to-cyan-50/30">
        <h3 className="text-lg font-semibold text-gray-900 mb-4 flex items-center">
          <div className="w-8 h-8 rounded-full bg-blue-100 flex items-center justify-center mr-2">
            <Calendar className="w-4 h-4 text-blue-600" />
          </div>
          Timeline
        </h3>
        <div className="space-y-4">
          {brief.timeline.map((phase, idx) => (
            <div key={idx} className="bg-white rounded-lg border-2 border-blue-200 p-4 hover:shadow-md transition-shadow">
              <div className="flex items-start justify-between mb-3">
                <h4 className="font-semibold text-blue-900 text-base">{phase.phase}</h4>
                <span className="px-3 py-1 bg-blue-100 text-blue-700 rounded-full text-sm font-medium">
                  {phase.duration}
                </span>
              </div>
              <div>
                <p className="text-xs font-semibold text-gray-600 mb-2">Deliverables:</p>
                <ul className="space-y-1">
                  {phase.deliverables.map((deliverable, i) => (
                    <li key={i} className="flex items-start space-x-2 text-sm text-gray-700">
                      <span className="text-blue-600 flex-shrink-0">→</span>
                      <span>{deliverable}</span>
                    </li>
                  ))}
                </ul>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Resources Needed */}
      <div className="p-6 border-b border-gray-100">
        <h3 className="text-lg font-semibold text-gray-900 mb-4 flex items-center">
          <div className="w-8 h-8 rounded-full bg-green-100 flex items-center justify-center mr-2">
            <Users className="w-4 h-4 text-green-600" />
          </div>
          Resources Needed
        </h3>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          {/* People & Skills */}
          <div className="bg-gradient-to-br from-green-50 to-emerald-50 rounded-lg p-4 border border-green-200">
            <h4 className="font-semibold text-green-900 mb-3 flex items-center">
              <Users className="w-4 h-4 mr-2" />
              People & Skills
            </h4>
            <ul className="space-y-2">
              {brief.resources.people.map((person, idx) => (
                <li key={idx} className="text-sm text-gray-700 flex items-start">
                  <span className="text-green-600 mr-2">•</span>
                  <span>{person}</span>
                </li>
              ))}
            </ul>
          </div>

          {/* Tools & Platforms */}
          <div className="bg-gradient-to-br from-indigo-50 to-blue-50 rounded-lg p-4 border border-indigo-200">
            <h4 className="font-semibold text-indigo-900 mb-3 flex items-center">
              <FileText className="w-4 h-4 mr-2" />
              Tools & Platforms
            </h4>
            <ul className="space-y-2">
              {brief.resources.tools.map((tool, idx) => (
                <li key={idx} className="text-sm text-gray-700 flex items-start">
                  <span className="text-indigo-600 mr-2">•</span>
                  <span>{tool}</span>
                </li>
              ))}
            </ul>
          </div>

          {/* Budget */}
          <div className="bg-gradient-to-br from-amber-50 to-yellow-50 rounded-lg p-4 border border-amber-200">
            <h4 className="font-semibold text-amber-900 mb-3 flex items-center">
              <DollarSign className="w-4 h-4 mr-2" />
              Budget
            </h4>
            <p className="text-sm text-gray-700">{brief.resources.budget}</p>
          </div>
        </div>
      </div>

      {/* Success Metrics */}
      <div className="p-6 border-b border-gray-100 bg-gradient-to-r from-green-50/30 to-emerald-50/30">
        <h3 className="text-lg font-semibold text-gray-900 mb-4 flex items-center">
          <div className="w-8 h-8 rounded-full bg-green-100 flex items-center justify-center mr-2">
            <TrendingUp className="w-4 h-4 text-green-600" />
          </div>
          Success Metrics
        </h3>
        <div className="space-y-3">
          {brief.successMetrics.map((metric, idx) => (
            <div key={idx} className="flex items-start space-x-3 p-3 bg-white rounded-lg border border-green-200">
              <span className="flex-shrink-0 w-6 h-6 rounded-full bg-green-600 text-white text-sm font-bold flex items-center justify-center">
                {idx + 1}
              </span>
              <span className="text-gray-700 flex-1">{metric}</span>
            </div>
          ))}
        </div>
      </div>

      {/* Risks & Mitigation */}
      <div className="p-6 border-b border-gray-100">
        <h3 className="text-lg font-semibold text-gray-900 mb-4 flex items-center">
          <div className="w-8 h-8 rounded-full bg-amber-100 flex items-center justify-center mr-2">
            <AlertTriangle className="w-4 h-4 text-amber-600" />
          </div>
          Risks & Mitigation
        </h3>
        <div className="space-y-4">
          {brief.risks.map((risk, idx) => (
            <div key={idx} className="bg-gradient-to-r from-amber-50 to-orange-50 rounded-lg p-4 border-2 border-amber-200">
              <div className="mb-2">
                <span className="inline-flex items-center px-2 py-1 bg-amber-600 text-white text-xs font-semibold rounded">
                  Risk {idx + 1}
                </span>
              </div>
              <p className="text-gray-800 font-medium mb-2">{risk.risk}</p>
              <div className="flex items-start space-x-2">
                <span className="text-green-600 font-semibold text-sm flex-shrink-0">Mitigation:</span>
                <span className="text-gray-700 text-sm">{risk.mitigation}</span>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Immediate Next Steps */}
      <div className="p-6 bg-gradient-to-r from-purple-50/30 to-pink-50/30">
        <h3 className="text-lg font-semibold text-gray-900 mb-4 flex items-center">
          <div className="w-8 h-8 rounded-full bg-purple-100 flex items-center justify-center mr-2">
            <Target className="w-4 h-4 text-purple-600" />
          </div>
          Immediate Next Steps
        </h3>
        <div className="space-y-3">
          {brief.nextSteps.map((step, idx) => (
            <div key={idx} className="flex items-start space-x-3 p-4 bg-white rounded-lg border-2 border-purple-200 hover:shadow-md transition-shadow">
              <span className="flex-shrink-0 w-6 h-6 rounded-full bg-purple-600 text-white text-sm font-bold flex items-center justify-center mt-0.5">
                {idx + 1}
              </span>
              <div className="flex-1">
                <span className="text-gray-800">{step.step}</span>
                <div className="flex items-center gap-2 mt-2">
                  <span className={`px-2 py-0.5 rounded-full text-xs font-medium ${
                    step.priority === 'high' ? 'bg-red-100 text-red-700' :
                    step.priority === 'medium' ? 'bg-yellow-100 text-yellow-700' :
                    'bg-green-100 text-green-700'
                  }`}>
                    {step.priority === 'high' ? '🔴' : step.priority === 'medium' ? '🟡' : '🟢'} {step.priority}
                  </span>
                  {step.owner && (
                    <span className="px-2 py-0.5 bg-gray-100 text-gray-700 rounded-full text-xs">
                      Owner: {step.owner}
                    </span>
                  )}
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Footer */}
      <div className="p-4 bg-gradient-to-r from-indigo-50 to-purple-50 text-center border-t border-indigo-100">
        <p className="text-sm text-gray-600 italic">
          Generated by FifthDraft Idea Studio
        </p>
      </div>
    </div>
  )
}
